import { ModeProvider } from '@/mode'
import type { Metadata } from 'next'
import './globals.scss'
import { useEffect, useRef } from 'react'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ModeProvider>
          {children}
        </ModeProvider>
      </body>
    </html>
  )
}
